rem rename all the files
ren "Volume 1\Disc 1 - Best of Bugs Bunny\01 - Baseball Bugs.avi" "Looney Tunes - S1946E02 - Baseball Bugs.*"
ren "Volume 1\Disc 1 - Best of Bugs Bunny\02 - Rabbit Seasoning.avi" "Looney Tunes - S1952E23 - Rabbit Seasoning.*"
ren "Volume 1\Disc 1 - Best of Bugs Bunny\03 - Long Haired Hare.avi" "Looney Tunes - S1949E16 - Long-Haired Hare.*"
ren "Volume 1\Disc 1 - Best of Bugs Bunny\04 - High Diving Hare.avi" "Looney Tunes - S1949E11 - High Diving Hare.*"
ren "Volume 1\Disc 1 - Best of Bugs Bunny\05 - Bully for Bugs.avi" "Looney Tunes - S1953E19 - Bully for Bugs.*"
ren "Volume 1\Disc 1 - Best of Bugs Bunny\06 - What's Up Doc.avi" "Looney Tunes - S1950E15 - What's Up Doc_.*"
ren "Volume 1\Disc 1 - Best of Bugs Bunny\07 - Rabbit's Kin.avi" "Looney Tunes - S1952E27 - Rabbit's Kin.*"
ren "Volume 1\Disc 1 - Best of Bugs Bunny\08 - Water, Water Every Hare.avi" "Looney Tunes - S1952E11 - Water, Water Every Hare.*"
ren "Volume 1\Disc 1 - Best of Bugs Bunny\09 - Big House Bunny.avi" "Looney Tunes - S1950E10 - Big House Bunny.*"
ren "Volume 1\Disc 1 - Best of Bugs Bunny\10 - Big Top Bunny.avi" "Looney Tunes - S1951E27 - Big Top Bunny.*"
ren "Volume 1\Disc 1 - Best of Bugs Bunny\11 - My Bunny Lies over the Sea.avi" "Looney Tunes - S1948E32 - My Bunny Lies over the Sea.*"
ren "Volume 1\Disc 1 - Best of Bugs Bunny\12 - Wabbit Trouble.avi" "Looney Tunes - S1941E40 - Wabbit Twouble.*"
ren "Volume 1\Disc 1 - Best of Bugs Bunny\13 - Ballot Box Bunny.avi" "Looney Tunes - S1951E23 - Ballot Box Bunny.*"
ren "Volume 1\Disc 1 - Best of Bugs Bunny\14 - Rabbit of Seville.avi" "Looney Tunes - S1950E30 - Rabbit of Seville.*"
ren "Volume 1\Disc 2 - Best of Daffy & Porky\01 - Duck Amuck.avi" "Looney Tunes - S1953E06 - Duck Amuck.*"
ren "Volume 1\Disc 2 - Best of Daffy & Porky\02 - Dough for the Do-Do.avi" "Looney Tunes - S1949E23 - Dough for the Do-Do.*"
ren "Volume 1\Disc 2 - Best of Daffy & Porky\03 - Drip-Along Daffy.avi" "Looney Tunes - S1951E26 - Drip-Along Daffy.*"
ren "Volume 1\Disc 2 - Best of Daffy & Porky\04 - Scaredy Cat.avi" "Looney Tunes - S1948E33 - Scaredy Cat.*"
ren "Volume 1\Disc 2 - Best of Daffy & Porky\05 - The Ducksters.avi" "Looney Tunes - S1950E21 - The Ducksters.*"
ren "Volume 1\Disc 2 - Best of Daffy & Porky\06 - The Scarlet Pumpernickle.avi" "Looney Tunes - S1950E06 - The Scarlet Pumpernickel.*"
ren "Volume 1\Disc 2 - Best of Daffy & Porky\07 - Yankee Doodle Daffy.avi" "Looney Tunes - S1943E14 - Yankee Doodle Daffy.*"
ren "Volume 1\Disc 2 - Best of Daffy & Porky\08 - Porky Chops.avi" "Looney Tunes - S1949E05 - Porky Chops.*"
ren "Volume 1\Disc 2 - Best of Daffy & Porky\09 - Wearing of the Grin.avi" "Looney Tunes - S1951E17 - The Wearing of the Grin.*"
ren "Volume 1\Disc 2 - Best of Daffy & Porky\10 - Deduce, You Say.avi" "Looney Tunes - S1956E23 - Deduce, You Say.*"
ren "Volume 1\Disc 2 - Best of Daffy & Porky\11 - Boobs in the Woods.avi" "Looney Tunes - S1950E03 - Boobs in the Woods.*"
ren "Volume 1\Disc 2 - Best of Daffy & Porky\12 - Golden Yeggs.avi" "Looney Tunes - S1950E18 - Golden Yeggs.*"
ren "Volume 1\Disc 2 - Best of Daffy & Porky\13 - Rabbit Fire.avi" "Looney Tunes - S1951E13 - Rabbit Fire.*"
ren "Volume 1\Disc 2 - Best of Daffy & Porky\14 - Duck Dodgers in the 24.5 Century.avi" "Looney Tunes - S1953E18 - Duck Dodgers in the 24th Century.*"
ren "Volume 1\Disc 3 - Looney Tunes All-Stars Part 1\01 - Elmer's Candid Camera.avi" "Looney Tunes - S1940E07 - Elmer's Candid Camera.*"
ren "Volume 1\Disc 3 - Looney Tunes All-Stars Part 1\02 - Bugs Bunny and the Three Bears.avi" "Looney Tunes - S1944E05 - Bugs Bunny and the Three Bears.*"
ren "Volume 1\Disc 3 - Looney Tunes All-Stars Part 1\03 - Fast and Furry-ous.avi" "Looney Tunes - S1949E24 - Fast and Furry-ous.*"
ren "Volume 1\Disc 3 - Looney Tunes All-Stars Part 1\04 - Hair-Raising Hare.avi" "Looney Tunes - S1946E10 - Hair-Raising Hare.*"
ren "Volume 1\Disc 3 - Looney Tunes All-Stars Part 1\05 - The Awful Orphan.avi" "Looney Tunes - S1949E04 - Awful Orphan.*"
ren "Volume 1\Disc 3 - Looney Tunes All-Stars Part 1\06 - Haredevil Hare.avi" "Looney Tunes - S1948E19 - Haredevil Hare.*"
ren "Volume 1\Disc 3 - Looney Tunes All-Stars Part 1\07 - For Scent-imental Reasons.avi" "Looney Tunes - S1949E29 - For Scent-imental Reasons.*"
ren "Volume 1\Disc 3 - Looney Tunes All-Stars Part 1\08 - Frigid Hare.avi" "Looney Tunes - S1949E26 - Frigid Hare.*"
ren "Volume 1\Disc 3 - Looney Tunes All-Stars Part 1\09 - The Hypo-Chondri-Cat.avi" "Looney Tunes - S1950E09 - The Hypo-Chondri-Cat.*"
ren "Volume 1\Disc 3 - Looney Tunes All-Stars Part 1\10 - Baton Bunny.avi" "Looney Tunes - S1959E01 - Baton Bunny.*"
ren "Volume 1\Disc 3 - Looney Tunes All-Stars Part 1\11 - Feed the Kitty.avi" "Looney Tunes - S1952E03 - Feed the Kitty.*"
ren "Volume 1\Disc 3 - Looney Tunes All-Stars Part 1\12 - Don't Give Up the Sheep.avi" "Looney Tunes - S1953E01 - Don't Give Up the Sheep.*"
ren "Volume 1\Disc 3 - Looney Tunes All-Stars Part 1\13 - Bugs Bunny Gets the Boid.avi" "Looney Tunes - S1942E22 - Bugs Bunny Gets the Boid.*"
ren "Volume 1\Disc 3 - Looney Tunes All-Stars Part 1\14 - Tortoise Wins by a Hare.avi" "Looney Tunes - S1943E04 - Tortoise Wins by a Hare.*"
ren "Volume 1\Disc 4 - Looney Tunes All-Stars Part 2\01 - Canary Row.avi" "Looney Tunes - S1950E24 - Canary Row.*"
ren "Volume 1\Disc 4 - Looney Tunes All-Stars Part 2\02 - Bunker Hill Bunny.avi" "Looney Tunes - S1950E23 - Bunker Hill Bunny.*"
ren "Volume 1\Disc 4 - Looney Tunes All-Stars Part 2\03 - Kit for Cat.avi" "Looney Tunes - S1948E29 - Kit for Cat.*"
ren "Volume 1\Disc 4 - Looney Tunes All-Stars Part 2\04 - Puddy Tat Trouble.avi" "Looney Tunes - S1951E05 - Putty Tat Trouble.*"
ren "Volume 1\Disc 4 - Looney Tunes All-Stars Part 2\05 - Bugs and Thugs.avi" "Looney Tunes - S1954E07 - Bugs and Thugs.*"
ren "Volume 1\Disc 4 - Looney Tunes All-Stars Part 2\06 - Canned Feud.avi" "Looney Tunes - S1951E03 - Canned Feud.*"
ren "Volume 1\Disc 4 - Looney Tunes All-Stars Part 2\07 - Lumber Jerks.avi" "Looney Tunes - S1955E16 - Lumber Jerks.*"
ren "Volume 1\Disc 4 - Looney Tunes All-Stars Part 2\08 - Speedy Gonzales.avi" "Looney Tunes - S1955E23 - Speedy Gonzales.*"
ren "Volume 1\Disc 4 - Looney Tunes All-Stars Part 2\09 - Tweety's S.O.S..avi" "Looney Tunes - S1951E22 - Tweety's S.O.S..*"
ren "Volume 1\Disc 4 - Looney Tunes All-Stars Part 2\10 - The Foghorn Leghorn.avi" "Looney Tunes - S1948E26 - The Foghorn Leghorn.*"
ren "Volume 1\Disc 4 - Looney Tunes All-Stars Part 2\11 - Daffy Duck Hunt.avi" "Looney Tunes - S1949E08 - Daffy Duck Hunt.*"
ren "Volume 1\Disc 4 - Looney Tunes All-Stars Part 2\12 - Early to Bet.avi" "Looney Tunes - S1951E12 - Early to Bet.*"
ren "Volume 1\Disc 4 - Looney Tunes All-Stars Part 2\13 - Broken Leghorn.avi" "Looney Tunes - S1959E18 - A Broken Leghorn.*"
ren "Volume 1\Disc 4 - Looney Tunes All-Stars Part 2\14 - Devil May Hare.avi" "Looney Tunes - S1954E15 - Devil May Hare.*"
ren "Volume 2\Disc 1 - Bugs Bunny Masterpieces\01 - The Big Snooze.avi" "Looney Tunes - S1946E21 - The Big Snooze.*"
ren "Volume 2\Disc 1 - Bugs Bunny Masterpieces\02 - Broomstick Bunny.avi" "Looney Tunes - S1956E05 - Broom-Stick Bunny.*"
ren "Volume 2\Disc 1 - Bugs Bunny Masterpieces\03 - Bugs Bunny Rides Again.avi" "Looney Tunes - S1948E15 - Bugs Bunny Rides Again.*"
ren "Volume 2\Disc 1 - Bugs Bunny Masterpieces\04 - Bunny Hugged.avi" "Looney Tunes - S1951E07 - Bunny Hugged.*"
ren "Volume 2\Disc 1 - Bugs Bunny Masterpieces\05 - French Rarebit.avi" "Looney Tunes - S1951E16 - French Rarebit.*"
ren "Volume 2\Disc 1 - Bugs Bunny Masterpieces\06 - Gorilla My Dreams.avi" "Looney Tunes - S1948E01 - Gorilla My Dreams.*"
ren "Volume 2\Disc 1 - Bugs Bunny Masterpieces\07 - The Hare-Brained Hypnotist.avi" "Looney Tunes - S1942E35 - The Hare-Brained Hypnotist.*"
ren "Volume 2\Disc 1 - Bugs Bunny Masterpieces\08 - Hare Conditioned.avi" "Looney Tunes - S1945E13 - Hare Conditioned.*"
ren "Volume 2\Disc 1 - Bugs Bunny Masterpieces\09 - The Heckling Hare.avi" "Looney Tunes - S1941E23 - The Heckling Hare.*"
ren "Volume 2\Disc 1 - Bugs Bunny Masterpieces\10 - Little Red Riding Rabbit.avi" "Looney Tunes - S1944E01 - Little Red Riding Rabbit.*"
ren "Volume 2\Disc 1 - Bugs Bunny Masterpieces\11 - Tortoise Beats Hare.avi" "Looney Tunes - S1941E09 - Tortoise Beats Hare.*"
ren "Volume 2\Disc 1 - Bugs Bunny Masterpieces\12 - Rabbit Transit.avi" "Looney Tunes - S1947E08 - Rabbit Transit.*"
ren "Volume 2\Disc 1 - Bugs Bunny Masterpieces\13 - Slick Hare.avi" "Looney Tunes - S1947E19 - Slick Hare.*"
ren "Volume 2\Disc 1 - Bugs Bunny Masterpieces\14 - Baby Buggy Bunny.avi" "Looney Tunes - S1954E30 - Baby Buggy Bunny.*"
ren "Volume 2\Disc 1 - Bugs Bunny Masterpieces\15 - Hyde and Hare.avi" "Looney Tunes - S1955E21 - Hyde and Hare.*"
ren "Volume 2\Disc 2 - Road Runner and Friends\01 - Beep Beep.avi" "Looney Tunes - S1952E08 - Beep Beep.*"
ren "Volume 2\Disc 2 - Road Runner and Friends\02 - Going! Going! Gosh!.avi" "Looney Tunes - S1952E12 - Going! Going! Gosh!.*"
ren "Volume 2\Disc 2 - Road Runner and Friends\03 - Zipping Along.avi" "Looney Tunes - S1953E23 - Zipping Along.*"
ren "Volume 2\Disc 2 - Road Runner and Friends\04 - Stop! Look! and Hasten!.avi" "Looney Tunes - S1954E20 - Stop! Look! and Hasten!.*"
ren "Volume 2\Disc 2 - Road Runner and Friends\05 - Ready, Set, Zoom.avi" "Looney Tunes - S1955E11 - Ready, Set, Zoom!.*"
ren "Volume 2\Disc 2 - Road Runner and Friends\06 - Guided Muscle.avi" "Looney Tunes - S1955E29 - Guided Muscle.*"
ren "Volume 2\Disc 2 - Road Runner and Friends\07 - Gee Whiz-z-z.avi" "Looney Tunes - S1956E11 - Gee Whiz-z-z-z-z-z-z.*"
ren "Volume 2\Disc 2 - Road Runner and Friends\08 - There They Go-Go-Go.avi" "Looney Tunes - S1956E26 - There They GO-GO-GO!.*"
ren "Volume 2\Disc 2 - Road Runner and Friends\09 - Scrambled Arches.avi" "Looney Tunes - S1957E03 - Scrambled Aches.*"
ren "Volume 2\Disc 2 - Road Runner and Friends\10 - Zoom and Bored.avi" "Looney Tunes - S1957E19 - Zoom and Bored.*"
ren "Volume 2\Disc 2 - Road Runner and Friends\11 - Whoa, Be Gone!.avi" "Looney Tunes - S1958E07 - Whoa, Be-Gone!.*"
ren "Volume 2\Disc 2 - Road Runner and Friends\12 - Cheese Chasers.avi" "Looney Tunes - S1951E20 - Cheese Chasers.*"
ren "Volume 2\Disc 2 - Road Runner and Friends\13 - The Dover Boys.avi" "Looney Tunes - S1942E31 - The Dover Boys.*"
ren "Volume 2\Disc 2 - Road Runner and Friends\14 - Mouse Wreckers.avi" "Looney Tunes - S1949E10 - Mouse Wreckers.*"
ren "Volume 2\Disc 2 - Road Runner and Friends\15 - A Bear for Punishment.avi" "Looney Tunes - S1951E24 - A Bear for Punishment.*"
ren "Volume 2\Disc 3 - Tweety and Sylvester and Friends\01 - Bad Ol' Putty Tat.avi" "Looney Tunes - S1949E19 - Bad Ol' Putty Tat.*"
ren "Volume 2\Disc 3 - Tweety and Sylvester and Friends\02 - All Abir-r-r-d.avi" "Looney Tunes - S1950E16 - All A Bir-r-r-d.*"
ren "Volume 2\Disc 3 - Tweety and Sylvester and Friends\03 - Room and Bird.avi" "Looney Tunes - S1951E14 - Room and Bird.*"
ren "Volume 2\Disc 3 - Tweety and Sylvester and Friends\04 - Tweet Tweet Tweety.avi" "Looney Tunes - S1951E28 - Tweet Tweet Tweety.*"
ren "Volume 2\Disc 3 - Tweety and Sylvester and Friends\05 - Gift Wrapped.avi" "Looney Tunes - S1952E04 - Gift Wrapped.*"
ren "Volume 2\Disc 3 - Tweety and Sylvester and Friends\06 - Ain't She Tweet.avi" "Looney Tunes - S1952E16 - Ain't She Tweet.*"
ren "Volume 2\Disc 3 - Tweety and Sylvester and Friends\07 - Bird in a Guilty Cage.avi" "Looney Tunes - S1952E21 - A Bird in a Guilty Cage.*"
ren "Volume 2\Disc 3 - Tweety and Sylvester and Friends\08 - Snow Business.avi" "Looney Tunes - S1953E02 - Snow Business.*"
ren "Volume 2\Disc 3 - Tweety and Sylvester and Friends\09 - Tweetie Pie.avi" "Looney Tunes - S1947E07 - Tweetie Pie.*"
ren "Volume 2\Disc 3 - Tweety and Sylvester and Friends\10 - Kitty Kornered.avi" "Looney Tunes - S1946E11 - Kitty Kornered.*"
ren "Volume 2\Disc 3 - Tweety and Sylvester and Friends\11 - Baby Bottleneck.avi" "Looney Tunes - S1946E05 - Baby Bottleneck.*"
ren "Volume 2\Disc 3 - Tweety and Sylvester and Friends\12 - Old Glory.avi" "Looney Tunes - S1939E22 - Old Glory.*"
ren "Volume 2\Disc 3 - Tweety and Sylvester and Friends\13 - The Great Piggy Bank Robbery.avi" "Looney Tunes - S1946E15 - The Great Piggy Bank Robbery.*"
ren "Volume 2\Disc 3 - Tweety and Sylvester and Friends\14 - Duck Soup to Nuts.avi" "Looney Tunes - S1944E12 - Duck Soup to Nuts.*"
ren "Volume 2\Disc 3 - Tweety and Sylvester and Friends\15 - Porky in Wackyland.avi" "Looney Tunes - S1938E29 - Porky in Wackyland.*"
ren "Volume 2\Disc 4 - Looney Tunes All-Stars On Stage and Screen\01 - Back Alley Uproar.avi" "Looney Tunes - S1948E08 - Back Alley Oproar.*"
ren "Volume 2\Disc 4 - Looney Tunes All-Stars On Stage and Screen\02 - Book Revue.avi" "Looney Tunes - S1946E01 - Book Revue.*"
ren "Volume 2\Disc 4 - Looney Tunes All-Stars On Stage and Screen\03 - A Corny Concerto.avi" "Looney Tunes - S1943E22 - A Corny Concerto.*"
ren "Volume 2\Disc 4 - Looney Tunes All-Stars On Stage and Screen\04 - Have You Got Any Castles.avi" "Looney Tunes - S1938E19 - Have You Got Any Castles_.*"
ren "Volume 2\Disc 4 - Looney Tunes All-Stars On Stage and Screen\05 - Hollywood Steps Out.avi" "Looney Tunes - S1941E17 - Hollywood Steps Out.*"
ren "Volume 2\Disc 4 - Looney Tunes All-Stars On Stage and Screen\06 - I Love to Singa.avi" "Looney Tunes - S1936E19 - I Love to Singa.*"
ren "Volume 2\Disc 4 - Looney Tunes All-Stars On Stage and Screen\07 - Katnip Kollege.avi" "Looney Tunes - S1938E17 - Katnip Kollege.*"
ren "Volume 2\Disc 4 - Looney Tunes All-Stars On Stage and Screen\08 - The Hep Cat.avi" "Looney Tunes - S1942E32 - The Hep Cat.*"
ren "Volume 2\Disc 4 - Looney Tunes All-Stars On Stage and Screen\09 - The Three Little Bops.avi" "Looney Tunes - S1957E01 - Three Little Bops.*"
ren "Volume 2\Disc 4 - Looney Tunes All-Stars On Stage and Screen\10 - One Froggy Evening.avi" "Looney Tunes - S1955E31 - One Froggy Evening.*"
ren "Volume 2\Disc 4 - Looney Tunes All-Stars On Stage and Screen\11 - Rhapsody Rabbit.avi" "Looney Tunes - S1946E24 - Rhapsody Rabbit.*"
ren "Volume 2\Disc 4 - Looney Tunes All-Stars On Stage and Screen\12 - Show Biz Bugs.avi" "Looney Tunes - S1957E22 - Show Biz Bugs.*"
ren "Volume 2\Disc 4 - Looney Tunes All-Stars On Stage and Screen\13 - Stage Door Cartoon.avi" "Looney Tunes - S1944E27 - Stage Door Cartoon.*"
ren "Volume 2\Disc 4 - Looney Tunes All-Stars On Stage and Screen\14 - What's Opera, Doc.avi" "Looney Tunes - S1957E14 - What's Opera, Doc_.*"
ren "Volume 2\Disc 4 - Looney Tunes All-Stars On Stage and Screen\15 - You Ought to be in Pictures.avi" "Looney Tunes - S1940E16 - You Ought to Be in Pictures.*"
ren "Volume 3\Disc 1 - Bugs Bunny Classics\01 - Hare Force.avi*" "Looney Tunes - S1944E17 - Hare Force.*"
ren "Volume 3\Disc 1 - Bugs Bunny Classics\02 - Hare Remover.avi*" "Looney Tunes - S1946E06 - Hare Remover.*"
ren "Volume 3\Disc 1 - Bugs Bunny Classics\03 - Hare Tonic.avi*" "Looney Tunes - S1945E17 - Hare Tonic.*"
ren "Volume 3\Disc 1 - Bugs Bunny Classics\04 - A Hare Grows in Manhatten.avi*" "Looney Tunes - S1947E05 - A Hare Grows in Manhattan.*"
ren "Volume 3\Disc 1 - Bugs Bunny Classics\05 - Easter Yeggs.avi*" "Looney Tunes - S1947E12 - Easter Yeggs.*"
ren "Volume 3\Disc 1 - Bugs Bunny Classics\06 - The Wabbit Who Came to Supper.avi*" "Looney Tunes - S1942E09 - The Wabbit Who Came to Supper.*"
ren "Volume 3\Disc 1 - Bugs Bunny Classics\07 - Bowery Bugs.avi*" "Looney Tunes - S1949E14 - Bowery Bugs.*"
ren "Volume 3\Disc 1 - Bugs Bunny Classics\08 - Homeless Hare.avi*" "Looney Tunes - S1950E07 - Homeless Hare.*"
ren "Volume 3\Disc 1 - Bugs Bunny Classics\09 - Case of the Missing Hare.avi*" "Looney Tunes - S1942E39 - Case of the Missing Hare.*"
ren "Volume 3\Disc 1 - Bugs Bunny Classics\10 - Acrobatty Bunny.avi*" "Looney Tunes - S1946E13 - Acrobatty Bunny.*"
ren "Volume 3\Disc 1 - Bugs Bunny Classics\11 - Wackiki Wabbit.avi*" "Looney Tunes - S1943E17 - Wackiki Wabbit.*"
ren "Volume 3\Disc 1 - Bugs Bunny Classics\12 - Hare Do.avi*" "Looney Tunes - S1949E02 - Hare Do.*"
ren "Volume 3\Disc 1 - Bugs Bunny Classics\13 - Rebel Rabbit.avi*" "Looney Tunes - S1949E09 - Rebel Rabbit.*"
ren "Volume 3\Disc 1 - Bugs Bunny Classics\14 - Hillbilly Hare.avi*" "Looney Tunes - S1950E19 - Hillbilly Hare.*"
ren "Volume 3\Disc 1 - Bugs Bunny Classics\15 - Duck! Rabbit, Duck!.avi*" "Looney Tunes - S1953E24 - Duck! Rabbit, Duck!.*"
ren "Volume 3\Disc 2 - Hollywood Caricatures and Parodies\01 - Daffy Duck in Hollywood.avi*" "Looney Tunes - S1938E37 - Daffy Duck in Hollywood.*"
ren "Volume 3\Disc 2 - Hollywood Caricatures and Parodies\02 - Hollywood Capers.avi*" "Looney Tunes - S1935E20 - Hollywood Capers.*"
ren "Volume 3\Disc 2 - Hollywood Caricatures and Parodies\03 - The CooCoo Nut Grove.avi*" "Looney Tunes - S1936E30 - The CooCoo Nut Grove.*"
ren "Volume 3\Disc 2 - Hollywood Caricatures and Parodies\04 - Porky's Road Race.avi*" "Looney Tunes - S1937E04 - Porky's Road Race.*"
ren "Volume 3\Disc 2 - Hollywood Caricatures and Parodies\05 - The Woods are Full of Cuckoos.avi*" "Looney Tunes - S1937E34 - The Woods Are Full of Cuckoos.*"
ren "Volume 3\Disc 2 - Hollywood Caricatures and Parodies\06 - She was an Acrobat's Daughter.avi*" "Looney Tunes - S1937E09 - She Was an Acrobat's Daughter.*"
ren "Volume 3\Disc 2 - Hollywood Caricatures and Parodies\07 - The Film Fan.avi*" "Looney Tunes - S1939E43 - The Film Fan.*"
ren "Volume 3\Disc 2 - Hollywood Caricatures and Parodies\08 - Speaking of the Weather.avi*" "Looney Tunes - S1937E25 - Speaking of the Weather.*"
ren "Volume 3\Disc 2 - Hollywood Caricatures and Parodies\09 - Thugs with Dirty Mugs.avi*" "Looney Tunes - S1939E15 - Thugs with Dirty Mugs.*"
ren "Volume 3\Disc 2 - Hollywood Caricatures and Parodies\10 - Goofy Groceries.avi*" "Looney Tunes - S1941E11 - Goofy Groceries.*"
ren "Volume 3\Disc 2 - Hollywood Caricatures and Parodies\11 - Swooner Crooner.avi*" "Looney Tunes - S1944E10 - Swooner Crooner.*"
ren "Volume 3\Disc 2 - Hollywood Caricatures and Parodies\12 - Wideo Wabbit.avi*" "Looney Tunes - S1956E25 - Wideo Wabbit.*"
ren "Volume 3\Disc 2 - Hollywood Caricatures and Parodies\13 - The Honey-Mousers.avi*" "Looney Tunes - S1956E28 - The Honey-Mousers.*"
ren "Volume 3\Disc 2 - Hollywood Caricatures and Parodies\14 - The Last Hungry Cat.avi*" "Looney Tunes - S1961E18 - The Last Hungry Cat.*"
ren "Volume 3\Disc 2 - Hollywood Caricatures and Parodies\15 - The Mouse that Jack Built.avi*" "Looney Tunes - S1959E06 - The Mouse That Jack Built.*"
ren "Volume 3\Disc 3 - Porky and the Pigs\01 - I Haven't Got a Hat.avi*" "Looney Tunes - S1935E04 - I Haven't Got a Hat.*"
ren "Volume 3\Disc 3 - Porky and the Pigs\02 - Porky's Romance.avi*" "Looney Tunes - S1937E08 - Porky's Romance.*"
ren "Volume 3\Disc 3 - Porky and the Pigs\03 - Porky's Party.avi*" "Looney Tunes - S1938E18 - Porky's Party.*"
ren "Volume 3\Disc 3 - Porky and the Pigs\04 - Porky in Egypt.avi*" "Looney Tunes - S1938E33 - Porky in Egypt.*"
ren "Volume 3\Disc 3 - Porky and the Pigs\05 - Porky and Teabiscuit.avi*" "Looney Tunes - S1939E14 - Porky and Teabiscuit.*"
ren "Volume 3\Disc 3 - Porky and the Pigs\06 - Pigs is Pigs.avi*" "Looney Tunes - S1937E03 - Pigs Is Pigs.*"
ren "Volume 3\Disc 3 - Porky and the Pigs\07 - Pigs in a Polka.avi*" "Looney Tunes - S1943E03 - Pigs in a Polka.*"
ren "Volume 3\Disc 3 - Porky and the Pigs\08 - Porky Pig's Feat.avi*" "Looney Tunes - S1943E18 - Porky Pig's Feat.*"
ren "Volume 3\Disc 3 - Porky and the Pigs\09 - Daffy Duck Slept Here.avi*" "Looney Tunes - S1948E06 - Daffy Duck Slept Here.*"
ren "Volume 3\Disc 3 - Porky and the Pigs\10 - Bye Bye Bluebeard.avi*" "Looney Tunes - S1949E28 - Bye, Bye Bluebeard.*"
ren "Volume 3\Disc 3 - Porky and the Pigs\11 - An Egg Scrambler.avi*" "Looney Tunes - S1950E13 - An Egg Scramble.*"
ren "Volume 3\Disc 3 - Porky and the Pigs\12 - Robin Hood Daffy.avi*" "Looney Tunes - S1958E05 - Robin Hood Daffy.*"
ren "Volume 3\Disc 3 - Porky and the Pigs\13 - The Windblown Hare.avi*" "Looney Tunes - S1949E22 - The Windblown Hare.*"
ren "Volume 3\Disc 3 - Porky and the Pigs\14 - Claws for Alarm.avi*" "Looney Tunes - S1954E13 - Claws For Alarm.*"
ren "Volume 3\Disc 3 - Porky and the Pigs\15 - Rocket Squad.avi*" "Looney Tunes - S1956E06 - Rocket Squad.*"
ren "Volume 3\Disc 4 - All-Stars Cartoon Party\01 - Daffy Duck and the Dinosaur.avi*" "Looney Tunes - S1939E13 - Daffy Duck and the Dinosaur.*"
ren "Volume 3\Disc 4 - All-Stars Cartoon Party\02 - Super Rabbit.avi*" "Looney Tunes - S1943E09 - Super-Rabbit.*"
ren "Volume 3\Disc 4 - All-Stars Cartoon Party\03 - Daffy Duck and Egghead.avi*" "Looney Tunes - S1938E01 - Daffy Duck & Egghead.*"
ren "Volume 3\Disc 4 - All-Stars Cartoon Party\04 - A Gruesome Twosome.avi*" "Looney Tunes - S1945E10 - A Gruesome Twosome.*"
ren "Volume 3\Disc 4 - All-Stars Cartoon Party\05 - Draftee Daffy.avi*" "Looney Tunes - S1945E03 - Draftee Daffy.*"
ren "Volume 3\Disc 4 - All-Stars Cartoon Party\06 - Falling Hare.avi*" "Looney Tunes - S1943E24 - Falling Hare.*"
ren "Volume 3\Disc 4 - All-Stars Cartoon Party\07 - Steal Wool.avi*" "Looney Tunes - S1957E12 - Steal Wool.*"
ren "Volume 3\Disc 4 - All-Stars Cartoon Party\08 - Birds Anonymous.avi*" "Looney Tunes - S1957E16 - Birds Anonymous.*"
ren "Volume 3\Disc 4 - All-Stars Cartoon Party\09 - No Barking.avi*" "Looney Tunes - S1954E06 - No Barking.*"
ren "Volume 3\Disc 4 - All-Stars Cartoon Party\10 - Rabbit Punch.avi*" "Looney Tunes - S1948E10 - Rabbit Punch.*"
ren "Volume 3\Disc 4 - All-Stars Cartoon Party\11 - An Itch In Time.avi*" "Looney Tunes - S1943E27 - An Itch in Time.*"
ren "Volume 3\Disc 4 - All-Stars Cartoon Party\12 - Odor-Able Kitty.avi*" "Looney Tunes - S1945E01 - Odor-Able Kitty.*"
ren "Volume 3\Disc 4 - All-Stars Cartoon Party\13 - Walky Talky Hawky.avi*" "Looney Tunes - S1946E18 - Walky Talky Hawky.*"
ren "Volume 3\Disc 4 - All-Stars Cartoon Party\14 - Gonzales' Tomales.avi*" "Looney Tunes - S1957E24 - Gonzales' Tamales.*"
ren "Volume 3\Disc 4 - All-Stars Cartoon Party\15 - To Beep or Not To Beep.avi*" "Looney Tunes - S1963E17 - To Beep or Not to Beep.*"
ren "Volume 4\Disc 1 - Bugs Bunny Favorites\01 - Roman-Legion Hare.avi" "Looney Tunes - S1955E27 - Roman Legion-Hare.*"
ren "Volume 4\Disc 1 - Bugs Bunny Favorites\02 - The Grey-Hounded Hare.avi" "Looney Tunes - S1949E20 - The Grey Hounded Hare.*"
ren "Volume 4\Disc 1 - Bugs Bunny Favorites\03 - Rabbit Hood.avi" "Looney Tunes - S1949E34 - Rabbit Hood.*"
ren "Volume 4\Disc 1 - Bugs Bunny Favorites\04 - Operation Rabbit.avi" "Looney Tunes - S1952E02 - Operation_ Rabbit.*"
ren "Volume 4\Disc 1 - Bugs Bunny Favorites\05 - Knight-Mare Hare.avi" "Looney Tunes - S1955E24 - Knight-Mare Hare.*"
ren "Volume 4\Disc 1 - Bugs Bunny Favorites\06 - Southern Fried Rabbit.avi" "Looney Tunes - S1953E11 - Southern Fried Rabbit.*"
ren "Volume 4\Disc 1 - Bugs Bunny Favorites\07 - Mississippi Hare.avi" "Looney Tunes - S1949E06 - Mississippi Hare.*"
ren "Volume 4\Disc 1 - Bugs Bunny Favorites\08 - Hurdy-Gurdy Hare.avi" "Looney Tunes - S1950E02 - Hurdy-Gurdy Hare.*"
ren "Volume 4\Disc 1 - Bugs Bunny Favorites\09 - Forward March Hare.avi" "Looney Tunes - S1953E04 - Forward March Hare.*"
ren "Volume 4\Disc 1 - Bugs Bunny Favorites\10 - Sahara Hare.avi" "Looney Tunes - S1955E08 - Sahara Hare.*"
ren "Volume 4\Disc 1 - Bugs Bunny Favorites\11 - Barbary Coast Bunny.avi" "Looney Tunes - S1956E17 - Barbary-Coast Bunny.*"
ren "Volume 4\Disc 1 - Bugs Bunny Favorites\12 - To Hare is Human.avi" "Looney Tunes - S1956E29 - To Hare is Human.*"
ren "Volume 4\Disc 1 - Bugs Bunny Favorites\13 - 8 Ball Bunny.avi" "Looney Tunes - S1950E14 - 8 Ball Bunny.*"
ren "Volume 4\Disc 1 - Bugs Bunny Favorites\14 - Knighty Knight Bugs.avi" "Looney Tunes - S1958E13 - Knighty Knight Bugs.*"
ren "Volume 4\Disc 1 - Bugs Bunny Favorites\15 - Rabbit Romeo.avi" "Looney Tunes - S1957E25 - Rabbit Romeo.*"
ren "Volume 4\Disc 2 - A Dash of Tashlin\01 - The Case of the Stuttering Pig.avi" "Looney Tunes - S1937E31 - The Case of the Stuttering Pig.*"
ren "Volume 4\Disc 2 - A Dash of Tashlin\02 - Little Pancho Vanilla.avi" "Looney Tunes - S1938E30 - Little Pancho Vanilla.*"
ren "Volume 4\Disc 2 - A Dash of Tashlin\03 - Little Beau Porky.avi" "Looney Tunes - S1936E29 - Little Beau Porky.*"
ren "Volume 4\Disc 2 - A Dash of Tashlin\04 - Now That Summer is Gone.avi" "Looney Tunes - S1938E13 - Now That Summer Is Gone.*"
ren "Volume 4\Disc 2 - A Dash of Tashlin\05 - Porky in the North Woods.avi" "Looney Tunes - S1936E32 - Porky in the North Woods.*"
ren "Volume 4\Disc 2 - A Dash of Tashlin\06 - You're an Education.avi" "Looney Tunes - S1938E34 - You're an Education.*"
ren "Volume 4\Disc 2 - A Dash of Tashlin\07 - Porky's Railroad.avi" "Looney Tunes - S1937E22 - Porky's Railroad.*"
ren "Volume 4\Disc 2 - A Dash of Tashlin\08 - Plane Daffy.avi" "Looney Tunes - S1944E22 - Plane Daffy.*"
ren "Volume 4\Disc 2 - A Dash of Tashlin\09 - Porky the Fireman.avi" "Looney Tunes - S1938E16 - Porky the Fireman.*"
ren "Volume 4\Disc 2 - A Dash of Tashlin\10 - Cracked Ice.avi" "Looney Tunes - S1938E27 - Cracked Ice.*"
ren "Volume 4\Disc 2 - A Dash of Tashlin\11 - Puss N' Booty.avi" "Looney Tunes - S1943E28 - Puss N' Booty.*"
ren "Volume 4\Disc 2 - A Dash of Tashlin\12 - I Got Plenty of Mutton.avi" "Looney Tunes - S1944E06 - I Got Plenty of Mutton.*"
ren "Volume 4\Disc 2 - A Dash of Tashlin\13 - Booby Hatched.avi" "Looney Tunes - S1944E24 - Booby Hatched.*"
ren "Volume 4\Disc 2 - A Dash of Tashlin\14 - Porky's Poultry Plant.avi" "Looney Tunes - S1936E22 - Porky's Poultry Plant.*"
ren "Volume 4\Disc 2 - A Dash of Tashlin\15 - The Stupid Cupid.avi" "Looney Tunes - S1944E26 - The Stupid Cupid.*"
ren "Volume 4\Disc 3 - Speedy Gonzales in a Flash\01 - Cat-tails for Two.avi" "Looney Tunes - S1953E21 - Cat-Tails For Two.*"
ren "Volume 4\Disc 3 - Speedy Gonzales in a Flash\02 - Tobasco Road.avi" "Looney Tunes - S1957E15 - Tabasco Road.*"
ren "Volume 4\Disc 3 - Speedy Gonzales in a Flash\03 - Tortilla Flaps.avi" "Looney Tunes - S1958E02 - Tortilla Flaps.*"
ren "Volume 4\Disc 3 - Speedy Gonzales in a Flash\04 - Mexicali Shmoes.avi" "Looney Tunes - S1959E12 - Mexicali Shmoes.*"
ren "Volume 4\Disc 3 - Speedy Gonzales in a Flash\05 - Here Today, Gone Tamle.avi" "Looney Tunes - S1959E16 - Here Today, Gone Tamale.*"
ren "Volume 4\Disc 3 - Speedy Gonzales in a Flash\06 - West of the Pesos.avi" "Looney Tunes - S1960E02 - West of the Pesos.*"
ren "Volume 4\Disc 3 - Speedy Gonzales in a Flash\07 - Cannery Woe.avi" "Looney Tunes - S1961E01 - Cannery Woe.*"
ren "Volume 4\Disc 3 - Speedy Gonzales in a Flash\08 - The Pied Piper of Guadalupe.avi" "Looney Tunes - S1961E13 - The Pied Piper of Guadalupe.*"
ren "Volume 4\Disc 3 - Speedy Gonzales in a Flash\09 - Mexican Boarders.avi" "Looney Tunes - S1962E06 - Mexican Boarders.*"
ren "Volume 4\Disc 3 - Speedy Gonzales in a Flash\10 - Chili Weather.avi" "Looney Tunes - S1963E11 - Chili Weather.*"
ren "Volume 4\Disc 3 - Speedy Gonzales in a Flash\11 - A Message to Gracias.avi" "Looney Tunes - S1964E02 - A Message To Gracias.*"
ren "Volume 4\Disc 3 - Speedy Gonzales in a Flash\12 - Nuts and Volts.avi" "Looney Tunes - S1964E06 - Nuts and Volts.*"
ren "Volume 4\Disc 3 - Speedy Gonzales in a Flash\13 - Pancho's Hideaway.avi" "Looney Tunes - S1964E12 - Pancho's Hideaway.*"
ren "Volume 4\Disc 3 - Speedy Gonzales in a Flash\14 - The Wild Chase.avi" "Looney Tunes - S1965E05 - The Wild Chase.*"
ren "Volume 4\Disc 3 - Speedy Gonzales in a Flash\15 - A Haunting We Will Go.avi" "Looney Tunes - S1966E09 - A-Haunting We Will Go.*"
ren "Volume 4\Disc 4 - Kitty Korner\01 - The Night Watchman.avi" "Looney Tunes - S1938E35 - The Night Watchman.*"
ren "Volume 4\Disc 4 - Kitty Korner\02 - Conrad the Sailor.avi" "Looney Tunes - S1942E07 - Conrad the Sailor.*"
ren "Volume 4\Disc 4 - Kitty Korner\03 - The Sour Puss.avi" "Looney Tunes - S1940E34 - The Sour Puss.*"
ren "Volume 4\Disc 4 - Kitty Korner\04 - The Aristo-Cat.avi" "Looney Tunes - S1943E16 - The Aristo-Cat.*"
ren "Volume 4\Disc 4 - Kitty Korner\05 - Dough Ray Me-ow.avi" "Looney Tunes - S1948E21 - Dough Ray Me-ow.*"
ren "Volume 4\Disc 4 - Kitty Korner\06 - Pizzicato Pussy Cat.avi" "Looney Tunes - S1955E01 - Pizzicato Pussycat.*"
ren "Volume 4\Disc 4 - Kitty Korner\07 - Kiss Me Cat.avi" "Looney Tunes - S1953E05 - Kiss Me Cat.*"
ren "Volume 4\Disc 4 - Kitty Korner\08 - Cat Feud.avi" "Looney Tunes - S1958E20 - Cat Feud.*"
ren "Volume 4\Disc 4 - Kitty Korner\09 - The Unexpected Pest.avi" "Looney Tunes - S1956E13 - The Unexpected Pest.*"
ren "Volume 4\Disc 4 - Kitty Korner\10 - Go Fly a Kit.avi" "Looney Tunes - S1957E05 - Go Fly a Kit.*"
ren "Volume 4\Disc 4 - Kitty Korner\11 - Kiddin' the Kitten.avi" "Looney Tunes - S1952E10 - Kiddin' the Kitten.*"
ren "Volume 4\Disc 4 - Kitty Korner\12 - A Peck O' Trouble.avi" "Looney Tunes - S1953E08 - A Peck O' Trouble.*"
ren "Volume 4\Disc 4 - Kitty Korner\13 - Mouse and Garden.avi" "Looney Tunes - S1960E11 - Mouse and Garden.*"
ren "Volume 4\Disc 4 - Kitty Korner\14 - Porky's Poor Fish.avi" "Looney Tunes - S1940E13 - Porky's Poor Fish.*"
ren "Volume 4\Disc 4 - Kitty Korner\15 - Swallow the Leader.avi" "Looney Tunes - S1949E27 - Swallow the Leader.*"
ren "Volume 5\Disc 1 - Bugs and Daffy\01 - 14-Carrot Rabbit.avi" "Looney Tunes - S1952E07 - 14 Carrot Rabbit.*"
ren "Volume 5\Disc 1 - Bugs and Daffy\02 - Ali Baba Bunny.avi" "Looney Tunes - S1957E04 - Ali Baba Bunny.*"
ren "Volume 5\Disc 1 - Bugs and Daffy\03 - Buccaneer Bunny.avi" "Looney Tunes - S1948E13 - Buccaneer Bunny.*"
ren "Volume 5\Disc 1 - Bugs and Daffy\04 - Bugs' Bonnets.avi" "Looney Tunes - S1956E01 - Bugs' Bonnets.*"
ren "Volume 5\Disc 1 - Bugs and Daffy\05 - A Star is Bored.avi" "Looney Tunes - S1956E22 - A Star is Bored.*"
ren "Volume 5\Disc 1 - Bugs and Daffy\06 - A Pest in the House.avi" "Looney Tunes - S1947E14 - A Pest in the House.*"
ren "Volume 5\Disc 1 - Bugs and Daffy\07 - Transylvania 6-5000.avi" "Looney Tunes - S1963E16 - Transylvania 6-5000.*"
ren "Volume 5\Disc 1 - Bugs and Daffy\08 - Oily Hare.avi" "Looney Tunes - S1952E17 - Oily Hare.*"
ren "Volume 5\Disc 1 - Bugs and Daffy\09 - Stupor Duck.avi" "Looney Tunes - S1956E16 - Stupor Duck.*"
ren "Volume 5\Disc 1 - Bugs and Daffy\10 - The Stupor Salesman.avi" "Looney Tunes - S1948E30 - The Stupor Salesman.*"
ren "Volume 5\Disc 1 - Bugs and Daffy\11 - The Abominable Snow Rabbit.avi" "Looney Tunes - S1961E08 - The Abominable Snow Rabbit.*"
ren "Volume 5\Disc 1 - Bugs and Daffy\12 - The Super Snooper.avi" "Looney Tunes - S1952E26 - The Super Snooper.*"
ren "Volume 5\Disc 1 - Bugs and Daffy\13 - The Upstanding Sitter.avi" "Looney Tunes - S1948E17 - The Up-Standing Sitter.*"
ren "Volume 5\Disc 1 - Bugs and Daffy\14 - Hollywood Daffy.avi" "Looney Tunes - S1946E12 - Hollywood Daffy.*"
ren "Volume 5\Disc 1 - Bugs and Daffy\15 - You Were Never Duckier.avi" "Looney Tunes - S1948E20 - You Were Never Duckier.*"
ren "Volume 5\Disc 2 - Fun-Filled Fairy Tales\01 - Bewitched Bunny.avi" "Looney Tunes - S1954E18 - Bewitched Bunny.*"
ren "Volume 5\Disc 2 - Fun-Filled Fairy Tales\02 - Paying the Piper.avi" "Looney Tunes - S1949E07 - Paying the Piper.*"
ren "Volume 5\Disc 2 - Fun-Filled Fairy Tales\03 - The Bear's Tale.avi" "Looney Tunes - S1940E11 - The Bear's Tale.*"
ren "Volume 5\Disc 2 - Fun-Filled Fairy Tales\04 - Foney Fables.avi" "Looney Tunes - S1942E24 - Foney Fables.*"
ren "Volume 5\Disc 2 - Fun-Filled Fairy Tales\05 - Goldimouse and the Three Cats.avi" "Looney Tunes - S1960E05 - Goldimouse and the Three Cats.*"
ren "Volume 5\Disc 2 - Fun-Filled Fairy Tales\06 - Holiday for Shoestrings.avi" "Looney Tunes - S1946E03 - Holiday for Shoestrings.*"
ren "Volume 5\Disc 2 - Fun-Filled Fairy Tales\07 - Little Red Rodent Hood.avi" "Looney Tunes - S1952E13 - Little Red Rodent Hood.*"
ren "Volume 5\Disc 2 - Fun-Filled Fairy Tales\08 - Little Red Walking Hood.avi" "Looney Tunes - S1937E32 - Little Red Walking Hood.*"
ren "Volume 5\Disc 2 - Fun-Filled Fairy Tales\09 - Red Riding Hoodwinked.avi" "Looney Tunes - S1955E26 - Red Riding Hoodwinked.*"
ren "Volume 5\Disc 2 - Fun-Filled Fairy Tales\10 - The Trial of Mr - Wolf.avi" "Looney Tunes - S1941E14 - The Trial of Mr. Wolf.*"
ren "Volume 5\Disc 2 - Fun-Filled Fairy Tales\11 - The Turn-Table Wolf.avi" "Looney Tunes - S1952E18 - The Turn-Tale Wolf.*"
ren "Volume 5\Disc 2 - Fun-Filled Fairy Tales\12 - Tom Thumb in Trouble.avi" "Looney Tunes - S1940E18 - Tom Thumb in Trouble.*"
ren "Volume 5\Disc 2 - Fun-Filled Fairy Tales\13 - Tweety and the Beanstalk.avi" "Looney Tunes - S1957E10 - Tweety and the Beanstalk.*"
ren "Volume 5\Disc 2 - Fun-Filled Fairy Tales\14 - A Gander and a Mother Goose.avi" "Looney Tunes - S1940E17 - A Gander at Mother Goose.*"
ren "Volume 5\Disc 2 - Fun-Filled Fairy Tales\15 - Senorella and the Glass Huarache.avi" "Looney Tunes - S1964E11 - Senorella And The Glass Huarache.*"
ren "Volume 5\Disc 3 - Putting a Bob Clampett on It\01 - Bacall to Arms.avi" "Looney Tunes - S1946E16 - Bacall to Arms.*"
ren "Volume 5\Disc 3 - Putting a Bob Clampett on It\02 - Buckaroo Bugs.avi" "Looney Tunes - S1944E20 - Buckaroo Bugs.*"
ren "Volume 5\Disc 3 - Putting a Bob Clampett on It\03 - Crazy Cruise.avi" "Looney Tunes - S1942E08 - Crazy Cruise.*"
ren "Volume 5\Disc 3 - Putting a Bob Clampett on It\04 - Farm Frolics.avi" "Looney Tunes - S1941E16 - Farm Frolics.*"
ren "Volume 5\Disc 3 - Putting a Bob Clampett on It\05 - Hare Ribbin'.avi" "Looney Tunes - S1944E15 - Hare Ribbin'.*"
ren "Volume 5\Disc 3 - Putting a Bob Clampett on It\06 - Patient Porky.avi" "Looney Tunes - S1940E26 - Patient Porky.*"
ren "Volume 5\Disc 3 - Putting a Bob Clampett on It\07 - Prehistoric Porky.avi" "Looney Tunes - S1940E31 - Prehistoric Porky.*"
ren "Volume 5\Disc 3 - Putting a Bob Clampett on It\08 - The Bashful Buzzard.avi" "Looney Tunes - S1945E15 - The Bashful Buzzard.*"
ren "Volume 5\Disc 3 - Putting a Bob Clampett on It\09 - The Old Grey Hare.avi" "Looney Tunes - S1944E25 - The Old Grey Hare.*"
ren "Volume 5\Disc 3 - Putting a Bob Clampett on It\10 - The Wacky Wabbit.avi" "Looney Tunes - S1942E14 - The Wacky Wabbit.*"
ren "Volume 5\Disc 3 - Putting a Bob Clampett on It\11 - The Wise Quacking Duck.avi" "Looney Tunes - S1943E11 - The Wise Quacking Duck.*"
ren "Volume 5\Disc 3 - Putting a Bob Clampett on It\12 - Wagon Heels.avi" "Looney Tunes - S1945E12 - Wagon Heels.*"
ren "Volume 5\Disc 3 - Putting a Bob Clampett on It\13 - The Daffy Doc.avi" "Looney Tunes - S1938E36 - The Daffy Doc.*"
ren "Volume 5\Disc 3 - Putting a Bob Clampett on It\14 - A Tale of Two Kitties.avi" "Looney Tunes - S1942E36 - A Tale of Two Kitties.*"
ren "Volume 5\Disc 3 - Putting a Bob Clampett on It\15 - Porky's Pooch.avi" "Looney Tunes - S1941E41 - Porky's Pooch.*"
ren "Volume 5\Disc 4 - The Early Daze\01 - Alpin Antics.avi" "Looney Tunes - S1936E06 - Alpine Antics.*"
ren "Volume 5\Disc 4 - The Early Daze\02 - Eatin' on the Cuff.avi" "Looney Tunes - S1942E28 - Eatin' on the Cuff or The Moth Who Came to Dinner.*"
ren "Volume 5\Disc 4 - The Early Daze\03 - Milk and Money.avi" "Looney Tunes - S1936E26 - Milk and Money.*"
ren "Volume 5\Disc 4 - The Early Daze\04 - I've Got to Sing a Torch Song.avi" "Looney Tunes - S1933E19 - I've Got to Sing a Torch Song.*"
ren "Volume 5\Disc 4 - The Early Daze\05 - Porky at the Crocadero.avi" "Looney Tunes - S1938E04 - Porky at the Crocadero.*"
ren "Volume 5\Disc 4 - The Early Daze\06 - Polar Pals.avi" "Looney Tunes - S1939E19 - Polar Pals.*"
ren "Volume 5\Disc 4 - The Early Daze\07 - Scrap Happy Daffy.avi" "Looney Tunes - S1943E20 - Scrap Happy Daffy.*"
ren "Volume 5\Disc 4 - The Early Daze\08 - Porky's Double Trouble.avi" "Looney Tunes - S1937E33 - Porky's Double Trouble.*"
ren "Volume 5\Disc 4 - The Early Daze\09 - Golddigers of '49.avi" "Looney Tunes - S1935E21 - Gold Diggers of '49.*"
ren "Volume 5\Disc 4 - The Early Daze\10 - Pilgrim Porky.avi" "Looney Tunes - S1940E08 - Pilgrim Porky.*"
ren "Volume 5\Disc 4 - The Early Daze\11 - Wise Quacks.avi" "Looney Tunes - S1939E26 - Wise Quacks.*"
ren "Volume 5\Disc 4 - The Early Daze\12 - Porky's Preview.avi" "Looney Tunes - S1941E13 - Porky's Preview.*"
ren "Volume 5\Disc 4 - The Early Daze\13 - Porky's Poppa.avi" "Looney Tunes - S1938E02 - Porky's Poppa.*"
ren "Volume 5\Disc 4 - The Early Daze\14 - Wholly Smoke.avi" "Looney Tunes - S1938E25 - Wholly Smoke.*"
ren "Volume 5\Disc 4 - The Early Daze\15 - What Price Porky.avi" "Looney Tunes - S1938E06 - What Price Porky.*"
ren "Volume 6\Disc 1 - Looney Tunes All-Stars\01 - Hare Trigger.avi" "Looney Tunes - S1945E08 - Hare Trigger.*"
ren "Volume 6\Disc 1 - Looney Tunes All-Stars\02 - To Duck or Not to Duck.avi" "Looney Tunes - S1943E05 - To Duck or Not to Duck.*"
ren "Volume 6\Disc 1 - Looney Tunes All-Stars\03 - Birth of a Notion.avi" "Looney Tunes - S1947E06 - Birth of a Notion.*"
ren "Volume 6\Disc 1 - Looney Tunes All-Stars\04 - My Little Duckaroo.avi" "Looney Tunes - S1954E28 - My Little Duckaroo.*"
ren "Volume 6\Disc 1 - Looney Tunes All-Stars\05 - Crowing Pains.avi" "Looney Tunes - S1947E13 - Crowing Pains.*"
ren "Volume 6\Disc 1 - Looney Tunes All-Stars\06 - Raw! Raw! Rooster!.avi" "Looney Tunes - S1956E20 - Raw! Raw! Rooster.*"
ren "Volume 6\Disc 1 - Looney Tunes All-Stars\07 - Heaven Scent.avi" "Looney Tunes - S1956E08 - Heaven Scent.*"
ren "Volume 6\Disc 1 - Looney Tunes All-Stars\08 - My Favorite Duck.avi" "Looney Tunes - S1942E38 - My Favorite Duck.*"
ren "Volume 6\Disc 1 - Looney Tunes All-Stars\09 - Jumpin' Jupiter.avi" "Looney Tunes - S1955E19 - Jumpin' Jupiter.*"
ren "Volume 6\Disc 1 - Looney Tunes All-Stars\10 - Satan's Waitin'.avi" "Looney Tunes - S1954E19 - Satan's Waitin'.*"
ren "Volume 6\Disc 1 - Looney Tunes All-Stars\11 - Hook Line and Stinker.avi" "Looney Tunes - S1958E16 - Hook, Line, and Stinker.*"
ren "Volume 6\Disc 1 - Looney Tunes All-Stars\12 - Bear Feat.avi" "Looney Tunes - S1949E32 - Bear Feat.*"
ren "Volume 6\Disc 1 - Looney Tunes All-Stars\13 - Dog Gone South.avi" "Looney Tunes - S1950E20 - Dog Gone South.*"
ren "Volume 6\Disc 1 - Looney Tunes All-Stars\14 - A Ham in a Role.avi" "Looney Tunes - S1949E33 - A Ham in a Role.*"
ren "Volume 6\Disc 1 - Looney Tunes All-Stars\15 - Often an Orphan.avi" "Looney Tunes - S1949E21 - Often an Orphan.*"
ren "Volume 6\Disc 2 - Patriotic Pals\01 - Herr Meets Hare.avi" "Looney Tunes - S1945E02 - Herr Meets Hare.*"
ren "Volume 6\Disc 2 - Patriotic Pals\02 - Russian Rhapsody.avi" "Looney Tunes - S1944E11 - Russian Rhapsody.*"
ren "Volume 6\Disc 2 - Patriotic Pals\03 - Daffy the Commando.avi" "Looney Tunes - S1943E26 - Daffy- The Commando.*"
ren "Volume 6\Disc 2 - Patriotic Pals\04 - Bosko the Doughboy.avi" "Looney Tunes - S1931E12 - Bosko the Doughboy.*"
ren "Volume 6\Disc 2 - Patriotic Pals\05 - Rookie Revue.avi" "Looney Tunes - S1941E35 - Rookie Revue.*"
ren "Volume 6\Disc 2 - Patriotic Pals\06 - The Draft Horse.avi" "Looney Tunes - S1942E15 - The Draft Horse.*"
ren "Volume 6\Disc 2 - Patriotic Pals\07 - Wacky Blackout.avi" "Looney Tunes - S1942E23 - Wacky Blackout.*"
ren "Volume 6\Disc 2 - Patriotic Pals\08 - The Ducktators.avi" "Looney Tunes - S1942E25 - The Ducktators.*"
ren "Volume 6\Disc 2 - Patriotic Pals\09 - The Weakly Reporter.avi" "Looney Tunes - S1944E07 - The Weakly Reporter.*"
ren "Volume 6\Disc 2 - Patriotic Pals\10 - Fifth Column Mouse.avi" "Looney Tunes - S1943E06 - The Fifth-Column Mouse.*"
ren "Volume 6\Disc 2 - Patriotic Pals\11 - Meet John Doughboy.avi" "Looney Tunes - S1941E22 - Meet John Doughboy.*"
ren "Volume 6\Disc 2 - Patriotic Pals\12 - Hollywood Canine Canteen.avi" "Looney Tunes - S1946E08 - Hollywood Canine Canteen.*"
ren "Volume 6\Disc 2 - Patriotic Pals\13 - By Word of Mouse.avi" "Looney Tunes - S1954E24 - By Word of Mouse.*"
ren "Volume 6\Disc 2 - Patriotic Pals\14 - Heir Conditioned.avi" "Looney Tunes - S1955E28 - Heir-Conditioned.*"
ren "Volume 6\Disc 2 - Patriotic Pals\15 - Yankee Dood it.avi" "Looney Tunes - S1956E24 - Yankee Dood It.*"
ren "Volume 6\Disc 3 - Bosko, Buddy and Merrie Melodies\01 - Congo Jazz.avi" "Looney Tunes - S1930E02 - Congo Jazz.*"
ren "Volume 6\Disc 3 - Bosko, Buddy and Merrie Melodies\02 - Smile Darn Ya, Smile!.avi" "Looney Tunes - S1931E09 - Smile, Darn Ya, Smile!.*"
ren "Volume 6\Disc 3 - Bosko, Buddy and Merrie Melodies\03 - The Booze Hangs High.avi" "Looney Tunes - S1930E04 - The Booze Hangs High.*"
ren "Volume 6\Disc 3 - Bosko, Buddy and Merrie Melodies\04 - One More Time.avi" "Looney Tunes - S1931E11 - One More Time.*"
ren "Volume 6\Disc 3 - Bosko, Buddy and Merrie Melodies\05 - Bosko's Picture Show.avi" "Looney Tunes - S1933E16 - Bosko's Picture Show.*"
ren "Volume 6\Disc 3 - Bosko, Buddy and Merrie Melodies\06 - You Don't Know What You're Doin'!.avi" "Looney Tunes - S1931E13 - You Don't Know What You're Doin'!.*"
ren "Volume 6\Disc 3 - Bosko, Buddy and Merrie Melodies\07 - We're in the Money!.avi" "Looney Tunes - S1933E15 - We're in the Money.*"
ren "Volume 6\Disc 3 - Bosko, Buddy and Merrie Melodies\08 - Ride 'em Bosko.avi" "Looney Tunes - S1932E20 - Ride Him, Bosko!.*"
ren "Volume 6\Disc 3 - Bosko, Buddy and Merrie Melodies\09 - Shuffle Off to Buffalo.avi" "Looney Tunes - S1933E13 - Shuffle Off to Buffalo.*"
ren "Volume 6\Disc 3 - Bosko, Buddy and Merrie Melodies\10 - Bosko in Person.avi" "Looney Tunes - S1933E04 - Bosko in Person.*"
ren "Volume 6\Disc 3 - Bosko, Buddy and Merrie Melodies\11 - The Dish Ran Away with the Spoon.avi" "Looney Tunes - S1933E14 - The Dish Ran Away with the Spoon.*"
ren "Volume 6\Disc 3 - Bosko, Buddy and Merrie Melodies\12 - Buddie's Day Out.avi" "Looney Tunes - S1933E17 - Buddy's Day Out.*"
ren "Volume 6\Disc 3 - Bosko, Buddy and Merrie Melodies\13 - Buddie's Beer Garden.avi" "Looney Tunes - S1933E21 - Buddy's Beer Garden.*"
ren "Volume 6\Disc 3 - Bosko, Buddy and Merrie Melodies\14 - Buddie's Circus.avi" "Looney Tunes - S1934E20 - Buddy's Circus.*"
ren "Volume 6\Disc 3 - Bosko, Buddy and Merrie Melodies\15 - A Cartoonist's Nightmare.avi" "Looney Tunes - S1935E18 - A Cartoonist's Nightmare.*"
ren "Volume 6\Disc 4 -  Most Requested Assorted Nuts and One-Shots\01 - Horton Hatches the Egg.avi" "Looney Tunes - S1942E11 - Horton Hatches the Egg.*"
ren "Volume 6\Disc 4 -  Most Requested Assorted Nuts and One-Shots\02 - Lights Fantastic.avi" "Looney Tunes - S1942E16 - Lights Fantastic.*"
ren "Volume 6\Disc 4 -  Most Requested Assorted Nuts and One-Shots\03 - Fresh Airedale.avi" "Looney Tunes - S1945E14 - Fresh Airedale.*"
ren "Volume 6\Disc 4 -  Most Requested Assorted Nuts and One-Shots\04 - Chow Hound.avi" "Looney Tunes - S1951E15 - Chow Hound.*"
ren "Volume 6\Disc 4 -  Most Requested Assorted Nuts and One-Shots\05 - The Oily American.avi" "Looney Tunes - S1954E17 - The Oily American.*"
ren "Volume 6\Disc 4 -  Most Requested Assorted Nuts and One-Shots\06 - It's Hummer Time.avi" "Looney Tunes - S1950E17 - It's Hummer Time.*"
ren "Volume 6\Disc 4 -  Most Requested Assorted Nuts and One-Shots\07 - Rocket Bye Baby.avi" "Looney Tunes - S1956E18 - Rocket-Bye Baby.*"
ren "Volume 6\Disc 4 -  Most Requested Assorted Nuts and One-Shots\08 - Goo Goo Goliath.avi" "Looney Tunes - S1954E23 - Goo Goo Goliath.*"
ren "Volume 6\Disc 4 -  Most Requested Assorted Nuts and One-Shots\09 - Wild Wife.avi" "Looney Tunes - S1954E05 - Wild Wife.*"
ren "Volume 6\Disc 4 -  Most Requested Assorted Nuts and One-Shots\10 - Much Ado About Nutting.avi" "Looney Tunes - S1953E13 - Much Ado About Nutting.*"
ren "Volume 6\Disc 4 -  Most Requested Assorted Nuts and One-Shots\11 - The Hole Idea.avi" "Looney Tunes - S1955E10 - The Hole Idea.*"
ren "Volume 6\Disc 4 -  Most Requested Assorted Nuts and One-Shots\12 - Now Hear This.avi" "Looney Tunes - S1963E06 - Now Hear This.*"
ren "Volume 6\Disc 4 -  Most Requested Assorted Nuts and One-Shots\13 - Martian Through Georgia.avi" "Looney Tunes - S1962E17 - Martian Through Georgia.*"
ren "Volume 6\Disc 4 -  Most Requested Assorted Nuts and One-Shots\14 - Page Miss Glory.avi" "Looney Tunes - S1936E05 - Page Miss Glory.*"
ren "Volume 6\Disc 4 -  Most Requested Assorted Nuts and One-Shots\15 - Norman Normal.avi" "Looney Tunes - S1968E02 - Norman Normal.*"